### ISSUE TITLE
I want to use packunused as a library

### ISSUE THREAD

**Issue by christian-marie** [hvr/packunused#11]
In order to incorporate packunused into a code-quality/pre-commit tool, I'd like to call it as a library.

I'm going to dump the source in as it currently is to get around this for now, however, we may be back later with a patch that exposes this as a library if you didn't already have plans for that.

The tool I am referring to is here:
https://github.com/anchor/git-vogue

**Comment by christian-marie** [comment]
Hmmn. On closer inspection it looks like this is going to be messy. I'd want to incorporate the prerequisite steps (run cabal build) into the library call itself. Have you thought about this?

**Comment by hvr** [comment]
tbh, have not thoughts (yet). anchor/git-vogue looks definitely interesting. Feel free to incorporate packunused (it's BSD3 after all -- you'd just need to add the original (c) notice, i.e. `LICENSE` to your source-tree somewhere) or submit me a PR to turn packunused into a library (I just have no time to do it myself)

**Comment by christian-marie** [comment]
Closing this, unlikely to get around to this in the near future. Thanks.
