### ISSUE TITLE
Cabal-1.22 ?

### ISSUE THREAD

**Issue by s9gf4ult** [hvr/packunused#12]
Hello, there is constrain `Cabal >=1.14 && <1.21` but Cabal-1.22 is already released. I can not use this beutifull tool with new Cabal and it is sad.

**Comment by hvr** [comment]
See #10 -- I'll merge it shortly

**Comment by hvr** [comment]
fyi, http://hackage.haskell.org/package/packunused-0.1.1.4

**Comment by s9gf4ult** [comment]
Ura!
