### ISSUE TITLE
Feature request: GHC 8.0 support

### ISSUE THREAD

**Issue by ryantrinkle** [hvr/packunused#24]

**Comment by nh2** [comment]
PR here: https://github.com/hvr/packunused/pull/23

But it's not going to work for GHC 8.0.1 because of this GHC bug I just found: https://ghc.haskell.org/trac/ghc/ticket/12474

**Comment by nh2** [comment]
CC @bgamari

**Comment by nh2** [comment]
The bug I filed will be fixed in GHC 8.0.2

**Comment by bgamari** [comment]
Merged #23.

**Comment by lwm** [comment]
Looks like this one can be closed off!

**Comment by hvr** [comment]
It makes sense to get a release for Hackage ready, now that we have GHC 8.0.2 around the corner...

**Comment by expipiplus1** [comment]
Has there been any progress on this?

**Comment by hvr** [comment]
[`packunused-0.1.2`](http://hackage.haskell.org/package/packunused-0.1.2) was just released; please reopen if this issue hasn't been resolved yet
