### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ndmitchell** [hvr/packunused#25]
I'd love to use this tool, but because of restrictions that means it has to be in Stackage. Is that possible?

**Comment by lwm** [comment]
I was able to `stack build packunused` but can't find it on Stackage ... confused :|

**Comment by ndmitchell** [comment]
I think it just takes your current global stackage setting and gives it a go, which for me fails. Certainly not very robust.

**Comment by hvr** [comment]
@ndmitchell what did/do you mean by "because of **restrictions** that means it has to be in Stackage"?

**Comment by ndmitchell** [comment]
@hvr, I meant restrictions in a corporate environment which is set up in particular ways with custom CI and installation stuff. I can happily use it at home and have done so.

**Comment by hvr** [comment]
@ndmitchell I see, well I don't mind it being in Stackage if somebody wants to add it, as long as it doesn't impose any additional overhead for me :-)

**Comment by lwm** [comment]
https://github.com/fpco/stackage#add-your-package = additional overhead for you @hvr. 

Don't mind taking co-/maintenance duty via Stackage if @ndmitchell isn't interested?

**Comment by ndmitchell** [comment]
I'm not interested. The burden is usually almost zero for well maintained packages - you just have to upgrade with your dependencies.

**Comment by lwm** [comment]
Merged in https://github.com/fpco/stackage/pull/2491 :+1:

**Comment by lwm** [comment]
I'm a bit spread thin these days and packunused has fallen out of the stackage nightlies. I'm gonna drop off trying to keep it there for now.

**Comment by ndmitchell** [comment]
FWIW, I use [weeder](https://hackage.haskell.org/package/weeder) now for this purpose, so I'm ambivalent as to whether it is in Stackage. I can imagine it would be useful for others, but closing this ticket and letting another interested user reopen it if they care.
