### ISSUE TITLE
Stackage candidate: Hackage not matching HEAD `build-depends`

### ISSUE THREAD

**Issue by lwm** [hvr/packunused#28]
Following from #25, I created https://github.com/fpco/stackage/pull/2140 and ended with the following errors:

```
Cabal-1.24.2.0 (Mikhail Glushenkov <mikhail.glushenkov@gmail.com> @23Skidoo) is out of bounds for:
- [ ] packunused-0.1.1.4 (>=1.14 && < 1.23). Luke Murphy <lukewm@riseup.net> @lwm. @hvr. Used by: executable

base-4.9.0.0 is out of bounds for:
- [ ] packunused-0.1.1.4 (>=4.5 && < 4.9). Luke Murphy <lukewm@riseup.net> @lwm. @hvr. Used by: executable
```

It appears the `packunused` on Hackage isn't up to date with HEAD here?

[Hackage `packunused.cabal`](http://hackage.haskell.org/package/packunused-0.1.1.4/packunused.cabal) vs. [Github `packunused.cabal`](https://github.com/hvr/packunused/blob/master/packunused.cabal#L81).

**Comment by lwm** [comment]
I am working on a PR which will solve the other bounds errors.

Maybe a new Hackage release can come soon?

**Comment by hvr** [comment]
@lwm yeah, I'm planning on a release since GHC 8.0.2 is around the corner

**Comment by lwm** [comment]
https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/8.0.2-notes.html

Huzzah! :)

**Comment by hvr** [comment]
[`packunused-0.1.2`](http://hackage.haskell.org/package/packunused-0.1.2) was just released; please reopen if this issue hasn't been resolved yet
